version: "3.3"
# 배포 전용 yml
# https://docs.docker.com/compose/extends/ 참고
# docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d

services:
  database:
    image: $DEEPMUSH_REGISTRY/deepmush_postgres:latest
    build: {}
    environment:
      - POSTGRES_USER=$DEEPMUSH_POSTGRES_USER
      - POSTGRES_PASSWORD=$DEEPMUSH_POSTGRES_PASSWORD
      - POSTGRES_DB=$DEEPMUSH_POSTGRES_DB

  pgadmin:
    expose:
      - "80"
    environment:
      PGADMIN_DEFAULT_EMAIL: $DEEPMUSH_PGADMIN_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $DEEPMUSH_PGADMIN_PASSWORD
      PGADMIN_LISTEN_PORT: 80
      VIRTUAL_HOST: pgadmin.deepmush.io

  mongodb:
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DEEPMUSH_MONGODB_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $DEEPMUSH_MONGODB_PASSWORD
      MONGO_INITDB_DATABASE: $DEEPMUSH_MONGODB_DB

  mongo-express:
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: $DEEPMUSH_MONGOEXPRESS_ADMIN_USERNAME
      ME_CONFIG_MONGODB_ADMINPASSWORD: $DEEPMUSH_MONGOEXPRESS_ADMIN_PASSWORD
      VIRTUAL_HOST: mongo-express.deepmush.io

  backend:
    image: $DEEPMUSH_REGISTRY/deepmush_backend:latest
    volumes:
      - ./production/secrets.json:/backend/secrets.json:ro
      - ./runs:/backend/runs
    environment:
      - USE_POSTGRES=1
      - IS_DOCKER=1
      - VIRTUAL_HOST=backend.deepmush.io

  # 아무것도 하지 않는 이미지로 변경
  # 실질적인 기능은 nginx-proxy가 대체함
  nginx:
    image: scratch
    ports: []
    networks: []
    depends_on: []

  migrate:
    depends_on: []
    image: $DEEPMUSH_REGISTRY/deepmush_backend:latest
    build: {}
    volumes:
      - ./production/secrets.json:/backend/secrets.json:ro

  worker:
    image: $DEEPMUSH_REGISTRY/deepmush_backend:latest
    volumes:
      - ./production/secrets.json:/backend/secrets.json:ro
      - ./runs:/backend/runs

  elk:
    expose:
      - "5601"
      - "9200"
      - "5044"
    ports: []
    networks:
      - elk-tier
    environment:
      - ELASTIC_PASSWORD=$DEEPMUSH_ELASTIC_PASSWORD
      - VIRTUAL_HOST=kibana.deepmush.io
      - VIRTUAL_PORT=5601

  cadvisor:
    expose:
      - "8080"
    environment:
      - VIRTUAL_HOST=cadvisor.deepmush.io

  prometheus:
    ports: []
    environment:
      - VIRTUAL_HOST=prometheus.deepmush.io

  grafana:
    ports: []
    expose:
      - "3000"
    volumes:
      - ./grafana/grafana.prod.ini:/etc/grafana/grafana.ini
      - ./data/grafana/grafana:/var/lib/grafana
      - ./data/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - VIRTUAL_HOST=grafana.deepmush.io

  node-exporter:
    environment:
      - VIRTUAL_HOST=node-exporter.deepmush.io
