version: "3.3"

services:
  database:
    container_name: database
    hostname: database
    user: ubuntu
    build: ./build/postgres
    expose:
      - "5432"
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./scripts:/scripts:ro
    networks:
      - db-tier
    environment:
      - POSTGRES_USER=deepmush
      - POSTGRES_PASSWORD=deepmush
      - POSTGRES_DB=deepmush

  backend:
    depends_on:
      - database
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    environment:
      - USE_POSTGRES=1
      - IS_DOCKER=1
    networks:
      - db-tier
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2G
        reservations:
          cpus: "0.5"
          memory: 512M
    tty: true

  worker:
    build:
      context: ./backend
      dockerfile: ./build/worker/Dockerfile
    volumes:
      - ./backend:/backend
    networks:
      - db-tier
    depends_on:
      - database
    environment:
      - USE_POSTGRES=1
      - IS_DOCKER=1
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2G
        reservations:
          cpus: "0.5"
          memory: 512M
    tty: true

networks:
  db-tier:
    driver: bridge
