version: "3.3"
# 개발 전용! 배포에서는 패스워드등 민감 정보 환경변수화된 prod.yml 필요

services:
  database:
    container_name: database
    hostname: database
    user: ubuntu
    build: ./build/postgres
    expose:
      - "5432"
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./scripts:/scripts:ro
    networks:
      - db-tier
    environment:
      - POSTGRES_USER=deepmush
      - POSTGRES_PASSWORD=deepmush
      - POSTGRES_DB=deepmush

  pgadmin:
    hostname: pgadmin
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    networks:
      - db-tier
      - nginx-tier
    environment:
      PGADMIN_DEFAULT_EMAIL: deepmush@deepmush.com
      PGADMIN_DEFAULT_PASSWORD: deepmush
      PGADMIN_LISTEN_PORT: 8082
    expose:
      - "8082"

  mongodb:
    container_name: mongodb
    hostname: mongodb
    image: mongo
    restart: always
    expose:
      - "27017"
    volumes:
      - ./mongo-db:/data/db
    networks:
      - db-tier
    environment:
      MONGO_INITDB_ROOT_USERNAME: deepmush
      MONGO_INITDB_ROOT_PASSWORD: deepmush
      MONGO_INITDB_DATABASE: deepmush

  mongo-express:
    hostname: mongo-express
    container_name: mongo-express
    image: mongo-express
    restart: always
    depends_on:
      - mongodb
    networks:
      - db-tier
      - nginx-tier
    expose:
      - "8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: deepmush
      ME_CONFIG_MONGODB_ADMINPASSWORD: deepmush

  backend:
    container_name: backend
    hostname: backend
    depends_on:
      - database
      - mongodb
    build: ./backend
    expose:
      - "8000"
    volumes:
      - ./backend:/backend
      - ../scripts:/scripts:ro
    environment:
      - USE_POSTGRES=1
      - IS_DOCKER=1
    networks:
      - db-tier
      - mq-tier
      - nginx-tier
    tty: true

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/config:/etc/nginx/conf.d:ro
      - ./nginx/logs:/var/log/nginx/
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    networks:
      - nginx-tier
    depends_on:
      - backend
      - pgadmin
      - mongo-express

  migrate:
    depends_on:
      - database
      - mongodb
    build: ./backend
    volumes:
      - ./backend:/backend
    environment:
      - USE_POSTGRES=1
      - IS_DOCKER=1
    networks:
      - db-tier
      - mq-tier
    entrypoint: "/bin/sh -c 'cd /backend ; while :; do python manage.py makemigrations ; python manage.py migrate ; sleep 15s ; done;'"
    tty: true

  rabbitmq:
    hostname: rabbitmq
    container_name: rabbitmq
    image: rabbitmq:3
    networks:
      - mq-tier
    expose:
      - "5672"

  worker:
    build:
      context: ./backend
    volumes:
      - ./backend:/backend
    entrypoint: "/bin/sh ./run-celery.sh"
    networks:
      - db-tier
      - mq-tier
    depends_on:
      - database
      - mongodb
    environment:
      - USE_POSTGRES=1
      - IS_DOCKER=1
    tty: true

networks:
  db-tier:
    driver: bridge
  mq-tier:
    driver: bridge
  nginx-tier:
    driver: bridge