version: "3.3"
# 배포 전용 yml
# https://docs.docker.com/compose/extends/ 참고
# docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d

services:
  database:
    image: deepmush_postgres:latest
    build: {}
    env_file:
      - ./production/env.env

  pgadmin:
    expose:
      - "80"
    env_file:
      - ./production/env.env
    environment:
      PGADMIN_LISTEN_PORT: 80
      VIRTUAL_HOST: pgadmin.deepmush.io

  mongodb:
    env_file:
      - ./production/env.env

  mongo-express:
    env_file:
      - ./production/env.env
    environment:
      VIRTUAL_HOST: mongo-express.deepmush.io

  backend:
    image: deepmush_backend:latest
    volumes:
      - ./production/secrets.json:/backend/secrets.json:ro
      - ./runs:/backend/runs
    environment:
      - USE_POSTGRES=1
      - IS_DOCKER=1
      - VIRTUAL_HOST=backend.deepmush.io

  # 아무것도 하지 않는 이미지로 변경
  # 실질적인 기능은 nginx-proxy가 대체함
  nginx:
    image: scratch
    ports: []
    networks: []
    depends_on: []

  migrate:
    depends_on: []
    image: deepmush_backend:latest
    build: {}
    volumes:
      - ./production/secrets.json:/backend/secrets.json:ro

  worker:
    image: deepmush_backend:latest
    volumes:
      - ./production/secrets.json:/backend/secrets.json:ro
      - ./runs:/backend/runs

  elk:
    expose:
      - "5601"
      - "9200"
      - "5044"
    ports: []
    networks:
      - elk-tier
    env_file:
      - ./production/env.env
    volumes:
      - ./data/elk-data:/var/lib/elasticsearch
      - ./logstash/input.local.conf:/etc/logstash/conf.d/03-input.conf
      - ./elastic/elasticsearch.prod.yml:/etc/elasticsearch/elasticsearch.yml
    environment:
      - VIRTUAL_HOST=kibana.deepmush.io
      - VIRTUAL_PORT=5601

  filebeat:
    image: deepmush_filebeat:latest
    build: {}
    volumes:
      - ./filebeat/filebeat.prod.yml:/usr/share/filebeat/filebeat.yml
      - ./nginx/logs:/var/log/nginx
      - ./backend/logs:/var/log/backend
      - /var/lib/docker/containers:/var/lib/docker/containers:ro

  cadvisor:
    ports: []
    expose:
      - "8080"

  prometheus:
    ports: []

  grafana:
    ports: []
    expose:
      - "3000"
    volumes:
      - ./grafana/grafana.prod.ini:/etc/grafana/grafana.ini
      - ./data/grafana/grafana:/var/lib/grafana
      - ./data/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - VIRTUAL_HOST=grafana.deepmush.io

  node-exporter:
    environment:
      - VIRTUAL_HOST=node-exporter.deepmush.io
