version: "3.3"
# 개발 전용! 배포에서는 패스워드등 민감 정보 환경변수화된 prod.yml 필요

services:
  database:
    image: bitnami/postgresql:latest
    expose:
      - "5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - db-tier
    environment:
      - POSTGRES_USER=deepmush
      - POSTGRES_PASSWORD=deepmush
      - POSTGRES_DB=deepmush
    tty: true

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    networks:
      - db-tier
    environment:
      PGADMIN_DEFAULT_EMAIL: deepmush@deepmush.com
      PGADMIN_DEFAULT_PASSWORD: deepmush
      PGADMIN_LISTEN_PORT: 8082
    ports:
      - "8082:8082"
    tty: true

  mongodb:
    image: mongo
    restart: always
    expose:
      - "27017"
    volumes:
      - mongodb:/data/db
    networks:
      - db-tier
    environment:
      MONGO_INITDB_ROOT_USERNAME: deepmush
      MONGO_INITDB_ROOT_PASSWORD: deepmush
      MONGO_INITDB_DATABASE: deepmush
    tty: true

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongodb
    networks:
      - db-tier
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: deepmush
      ME_CONFIG_MONGODB_ADMINPASSWORD: deepmush
    tty: true

  backend:
    depends_on:
      - database
      - mongodb
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    environment:
      - USE_POSTGRES=1
      - IS_DOCKER=1
    networks:
      - db-tier
      - mq-tier
    dns:
      - 8.8.8.8
      - 4.4.4.4
      - 1.1.1.1
    tty: true

  migrate:
    depends_on:
      - database
      - mongodb
    build: ./backend
    volumes:
      - ./backend:/backend
    environment:
      - USE_POSTGRES=1
      - IS_DOCKER=1
    networks:
      - db-tier
      - mq-tier
    entrypoint: "/bin/sh -c 'cd /backend ; while :; do python manage.py
      makemigrations ; python manage.py migrate ; sleep 15s ; done;'"
    tty: true

  rabbitmq:
    image: rabbitmq:3
    networks:
      - mq-tier
    expose:
      - "5672"
    tty: true

  worker:
    build:
      context: ./backend
    volumes:
      - ./backend:/backend
    entrypoint: "/bin/sh ./run-celery.sh"
    networks:
      - db-tier
      - mq-tier
    depends_on:
      - database
      - mongodb
    environment:
      - USE_POSTGRES=1
      - IS_DOCKER=1
    dns:
      - 8.8.8.8
      - 4.4.4.4
      - 1.1.1.1
    tty: true

networks:
  db-tier:
    driver: bridge
  mq-tier:
    driver: bridge

volumes:
  mongodb:
  db: