apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: database
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: database
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/db-tier: "true"
        io.kompose.service: database
    spec:
      containers:
        - command:
          - sudo chmod -R 700 /var/lib/postgresql/data
          - sudo chown -R $(whoami) /var/lib/postgresql/data
          - postgres
        - env:
            - name: ELASTIC_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: ELASTIC_PASSWORD
                  name: production-env-env
            - name: ELASTIC_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: ELASTIC_USERNAME
                  name: production-env-env
            - name: ME_CONFIG_BASICAUTH_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: ME_CONFIG_BASICAUTH_PASSWORD
                  name: production-env-env
            - name: ME_CONFIG_BASICAUTH_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: ME_CONFIG_BASICAUTH_USERNAME
                  name: production-env-env
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                configMapKeyRef:
                  key: ME_CONFIG_MONGODB_ADMINPASSWORD
                  name: production-env-env
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                configMapKeyRef:
                  key: ME_CONFIG_MONGODB_ADMINUSERNAME
                  name: production-env-env
            - name: ME_CONFIG_MONGODB_SERVER
              valueFrom:
                configMapKeyRef:
                  key: ME_CONFIG_MONGODB_SERVER
                  name: production-env-env
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: MONGO_INITDB_DATABASE
                  name: production-env-env
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MONGO_INITDB_ROOT_PASSWORD
                  name: production-env-env
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: MONGO_INITDB_ROOT_USERNAME
                  name: production-env-env
            - name: PGADMIN_DEFAULT_EMAIL
              valueFrom:
                configMapKeyRef:
                  key: PGADMIN_DEFAULT_EMAIL
                  name: production-env-env
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: PGADMIN_DEFAULT_PASSWORD
                  name: production-env-env
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: production-env-env
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: production-env-env
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: production-env-env
          image: a891/deepmush_postgres:latest
          name: database
          ports:
            - containerPort: 5432
          resources: {}
          tty: true
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: database-data
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /var/local/deepmush/db
          name: database-data
status: {}
