apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: elk
  name: elk
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: elk
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/elk-tier: "true"
        io.kompose.service: elk
    spec:
      containers:
        - env:
            - name: ELASTIC_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: ELASTIC_PASSWORD
                  name: production-env-env
            - name: ELASTIC_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: ELASTIC_USERNAME
                  name: production-env-env
            - name: ME_CONFIG_BASICAUTH_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: ME_CONFIG_BASICAUTH_PASSWORD
                  name: production-env-env
            - name: ME_CONFIG_BASICAUTH_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: ME_CONFIG_BASICAUTH_USERNAME
                  name: production-env-env
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                configMapKeyRef:
                  key: ME_CONFIG_MONGODB_ADMINPASSWORD
                  name: production-env-env
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                configMapKeyRef:
                  key: ME_CONFIG_MONGODB_ADMINUSERNAME
                  name: production-env-env
            - name: ME_CONFIG_MONGODB_SERVER
              valueFrom:
                configMapKeyRef:
                  key: ME_CONFIG_MONGODB_SERVER
                  name: production-env-env
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: MONGO_INITDB_DATABASE
                  name: production-env-env
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MONGO_INITDB_ROOT_PASSWORD
                  name: production-env-env
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: MONGO_INITDB_ROOT_USERNAME
                  name: production-env-env
            - name: PGADMIN_DEFAULT_EMAIL
              valueFrom:
                configMapKeyRef:
                  key: PGADMIN_DEFAULT_EMAIL
                  name: production-env-env
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: PGADMIN_DEFAULT_PASSWORD
                  name: production-env-env
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: production-env-env
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: production-env-env
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: production-env-env
          image: sebp/elk
          name: elk
          ports:
            - containerPort: 5601
            - containerPort: 9200
            - containerPort: 5044
          resources: {}
          tty: true
          volumeMounts:
            - mountPath: /var/lib/elasticsearch
              name: elk-lib
            - mountPath: /etc/logstash/conf.d/03-input.conf
              name: elk-conf
            - mountPath: /etc/elasticsearch/elasticsearch.yml
              name: elk-yml
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      dnsConfig:
        nameservers:
          - 8.8.8.8
      volumes:
        - hostPath:
            path: /var/local/deepmush/data/elk-data
          name: elk-lib
        - hostPath:
            path: /var/local/deepmush/logstash/input.local.conf
            type: FileOrCreate
          name: elk-conf
        - hostPath:
            path: /var/local/deepmush/elastic/elasticsearch.prod.yml
            type: FileOrCreate
          name: elk-yml
status: {}
