apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: null
  name: elk-tier
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              io.kompose.network/elk-tier: "true"
  podSelector:
    matchLabels:
      io.kompose.network/elk-tier: "true"
