apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: filebeat
  name: filebeat
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: filebeat
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        io.kompose.network/elk-tier: "true"
        io.kompose.service: filebeat
    spec:
      containers:
        - command:
            - /bin/sh
            - -c
            - >
                sleep 60s ;
                filebeat setup ;
                filebeat -e ;
                filebeat
          image: a891/deepmush_filebeat:latest
          name: filebeat
          resources: {}
          tty: true
          volumeMounts:
            - mountPath: /usr/share/filebeat
              name: filebeat-share
            - mountPath: /var/log/nginx
              name: filebeat-nginx
            - mountPath: /var/log/backend
              name: filebeat-backend
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      dnsConfig:
        nameservers:
          - 8.8.8.8
      volumes:
        - name: filebeat-share
          secret:
            secretName: filebeat-share
        - name: filebeat-nginx
          persistentVolumeClaim:
            claimName: nginx-logs-claim
        - name: filebeat-backend
          persistentVolumeClaim:
            claimName: backend-logs-claim
status: {}
