apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: migrate
  name: migrate
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: migrate
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/db-tier: "true"
        io.kompose.network/mq-tier: "true"
        io.kompose.service: migrate
    spec:
      containers:
        - command:
            - /bin/sh
            - -c
            - cd /backend ; while :; do sleep 60s ; python manage.py makemigrations ; python manage.py migrate --run-syncdb ; python manage.py migrate --run-syncdb --database=mongodb; done;
          env:
            - name: IS_DOCKER
              value: "1"
            - name: USE_POSTGRES
              value: "1"
          image: a891/deepmush_backend:latest
          name: migrate
          resources: {}
          tty: true
          volumeMounts:
            - mountPath: /backend/secrets.json
              name: migrate-secrets-json
              readOnly: true
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /var/local/deepmush/production/secrets.json
          name: migrate-secrets-json
status: {}
