apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mongo-express
  name: mongo-express
spec:
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  selector:
    io.kompose.service: mongo-express
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: mongo-express
  name: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo-express
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/db-tier: "true"
        io.kompose.service: mongo-express
    spec:
      containers:
        - envFrom:
          - configMapRef:
              name: production-env-env
          image: mongo-express
          name: mongo-express
          ports:
            - containerPort: 8081
          resources: {}
          tty: true
      restartPolicy: Always
status: {}
