apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: null
  name: mq-tier
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              io.kompose.network/mq-tier: "true"
  podSelector:
    matchLabels:
      io.kompose.network/mq-tier: "true"
