apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-runs-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path-retain