apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-data-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-path-retain