apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-lib-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path-retain