apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-provisioning-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path