apiVersion: v1
data:
  ELASTIC_PASSWORD: TEMPLATE_PLACEHOLDER
  ELASTIC_USERNAME: TEMPLATE_PLACEHOLDER
  ME_CONFIG_BASICAUTH_PASSWORD: TEMPLATE_PLACEHOLDER
  ME_CONFIG_BASICAUTH_USERNAME: TEMPLATE_PLACEHOLDER
  ME_CONFIG_MONGODB_ADMINPASSWORD: TEMPLATE_PLACEHOLDER
  ME_CONFIG_MONGODB_ADMINUSERNAME: TEMPLATE_PLACEHOLDER
  ME_CONFIG_MONGODB_SERVER: TEMPLATE_PLACEHOLDER
  MONGO_INITDB_DATABASE: TEMPLATE_PLACEHOLDER
  MONGO_INITDB_ROOT_PASSWORD: TEMPLATE_PLACEHOLDER
  MONGO_INITDB_ROOT_USERNAME: TEMPLATE_PLACEHOLDER
  PGADMIN_DEFAULT_EMAIL: TEMPLATE_PLACEHOLDER
  PGADMIN_DEFAULT_PASSWORD: TEMPLATE_PLACEHOLDER
  POSTGRES_DB: TEMPLATE_PLACEHOLDER
  POSTGRES_PASSWORD: TEMPLATE_PLACEHOLDER
  POSTGRES_USER: TEMPLATE_PLACEHOLDER
  USE_POSTGRES: "1"
  USE_DOCKER: "1"
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: backend-production-env-env
  name: production-env-env
